// server.js — Express API wrapping the simc binary
// POST /api/simulate  { profile: string, options: { ... } }
// GET  /api/health

const express = require("express");
const cors    = require("cors");
const { execFile } = require("child_process");
const fs   = require("fs");
const path = require("path");
const os   = require("os");
const crypto = require("crypto");

const app  = express();
const PORT = process.env.PORT || 3000;

const ALLOWED_ORIGINS = [
  /^https:\/\/[\w-]+\.github\.io$/,
  /^http:\/\/localhost(:\d+)?$/,
  /^http:\/\/127\.0\.0\.1(:\d+)?$/,
];

app.use(cors({
  origin: (origin, cb) => {
    if (!origin) return cb(null, true);
    const ok = ALLOWED_ORIGINS.some(r => r.test(origin));
    cb(ok ? null : new Error("Not allowed by CORS"), ok);
  }
}));

app.use(express.json({ limit: "64kb" }));

const SIMC_BIN = process.env.SIMC_BIN
  || path.join(__dirname, "..", "simc");

// ─── Helpers ─────────────────────────────────────────────────────────────────

function sanitizeInt(val, def, min, max) {
  const n = parseInt(val, 10);
  if (isNaN(n)) return def;
  return Math.min(Math.max(n, min), max);
}

function sanitizeFloat(val, def, min, max) {
  const n = parseFloat(val);
  if (isNaN(n)) return def;
  return Math.min(Math.max(n, min), max);
}

const VALID_FIGHT_STYLES = new Set(["Patchwerk", "HelterSkelter", "Ultraxion", "LightMovement", "HeavyMovement"]);

// Parse simc stdout for DPS and scale factors.
// simc 335-1 outputs scale factors in the format:
//   Gains (EP):
//     Agi=1.23  AP=0.45  Hit=2.34 ...
function parseSimcOutput(stdout) {
  const result = { dps: null, weights: {}, raw: stdout };

  // DPS: look for "DPS=12345.67" anywhere in output
  const dpsMatch = stdout.match(/\bDPS=([0-9.]+)/);
  if (dpsMatch) result.dps = parseFloat(dpsMatch[1]);

  // Scale factors — try "Scale Factors:" block first (space-separated key=val)
  const sfBlock = stdout.match(/Scale Factors:([\s\S]*?)(?:\n\n|\nSimulation|\nDPS Ranking|$)/);
  if (sfBlock) {
    const tokens = sfBlock[1].match(/(\w+)=([0-9.+-]+)/g) || [];
    tokens.forEach(t => {
      const [k, v] = t.split("=");
      result.weights[k] = parseFloat(v);
    });
  }

  // Fallback: "Gains (EP):" columnar table
  if (Object.keys(result.weights).length === 0) {
    const epMatch = stdout.match(/Gains \(EP\):([\s\S]*?)(?:\n\n|$)/);
    if (epMatch) {
      const tokens = epMatch[1].match(/(\w+)=([0-9.+-]+)/g) || [];
      tokens.forEach(t => {
        const [k, v] = t.split("=");
        result.weights[k] = parseFloat(v);
      });
      // Also try whitespace-separated rows
      if (Object.keys(result.weights).length === 0) {
        epMatch[1].split("\n").forEach(row => {
          const parts = row.trim().split(/\s+/);
          if (parts.length >= 2 && !isNaN(parseFloat(parts[1]))) {
            result.weights[parts[0]] = parseFloat(parts[1]);
          }
        });
      }
    }
  }

  return result;
}

// Build the full .simc profile from the user's TopFit export + sim options.
// All simc global options go in the header before the character block.
function buildProfile(exportText, options) {
  const {
    targetLevel,
    iterations,
    threads,
    scaleOnly,
    maxTime,
    varyCombatLength,
    fightStyle,
    playerSkill,
    calculateWeights,
  } = options;

  const lines = [
    `# Generated by simc-triumvirate`,
    `iterations=${iterations}`,
    `threads=${threads}`,
    `target_level=${targetLevel}`,
    `max_time=${maxTime}`,
    `vary_combat_length=${varyCombatLength}`,
    `fight_style=${fightStyle}`,
    `skill=${(playerSkill / 100).toFixed(2)}`,
  ];

  if (calculateWeights) {
    lines.push(`calculate_scale_factors=1`);
    if (scaleOnly && scaleOnly !== "none") {
      lines.push(`scale_only=${scaleOnly}`);
    }
  } else {
    lines.push(`calculate_scale_factors=0`);
  }

  lines.push(``); // blank line before character block
  return lines.join("\n") + exportText;
}

// ─── Routes ──────────────────────────────────────────────────────────────────

app.get("/api/health", (_req, res) => {
  res.json({ ok: true, simc: SIMC_BIN });
});

app.post("/api/simulate", (req, res) => {
  const { profile: rawProfile, options: rawOptions = {} } = req.body || {};

  if (!rawProfile || typeof rawProfile !== "string") {
    return res.status(400).json({ error: "Missing profile text" });
  }
  if (rawProfile.length > 32768) {
    return res.status(400).json({ error: "Profile too large (max 32KB)" });
  }

  // Sanitize and validate all options
  const fightStyle = VALID_FIGHT_STYLES.has(rawOptions.fight_style)
    ? rawOptions.fight_style
    : "Patchwerk";

  const options = {
    targetLevel:      sanitizeInt(rawOptions.targetLevel,       63,   1,  83),
    iterations:       sanitizeInt(rawOptions.iterations,        5000, 100, 50000),
    threads:          sanitizeInt(rawOptions.threads,           2,    1,  8),
    maxTime:          sanitizeInt(rawOptions.max_time,          300,  30, 3600),
    varyCombatLength: sanitizeFloat(rawOptions.vary_combat_length, 0, 0, 60),
    playerSkill:      sanitizeInt(rawOptions.player_skill,      100,  1,  100),
    fightStyle,
    scaleOnly:        typeof rawOptions.scaleOnly === "string" ? rawOptions.scaleOnly : "",
    calculateWeights: rawOptions.calculateWeights !== false,
  };

  const profileText = buildProfile(rawProfile, options);

  // Write temp file, run simc, cleanup
  const tmpFile = path.join(os.tmpdir(), `simc-${crypto.randomUUID()}.simc`);
  fs.writeFileSync(tmpFile, profileText, "utf8");

  // Timeout: more iterations + scale factors = more time needed
  const sfMultiplier = options.calculateWeights ? (options.scaleOnly.split(",").length || 1) + 1 : 1;
  const timeout = Math.max(60000, options.iterations * sfMultiplier * 5);

  console.log(`[sim] ${fightStyle} ${options.maxTime}s target=${options.targetLevel} iter=${options.iterations} sf=${options.calculateWeights}`);

  execFile(SIMC_BIN, [tmpFile], { timeout }, (err, stdout, stderr) => {
    fs.unlink(tmpFile, () => {});

    if (err && !stdout) {
      console.error("simc error:", err.message, stderr?.slice(0, 500));
      return res.status(500).json({
        error: "Simulation failed",
        detail: stderr || err.message,
      });
    }

    const parsed = parseSimcOutput(stdout);
    res.json({
      ok: true,
      dps: parsed.dps,
      weights: parsed.weights,
      rawOutput: stdout,
    });
  });
});

// ─── Start ───────────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`simc-triumvirate backend running on port ${PORT}`);
  console.log(`simc binary: ${SIMC_BIN}`);
});
