// server.js — Express API wrapping the simc binary
// POST /api/simulate  { profile: string, options: { targetLevel, iterations, threads } }
// GET  /api/health

const express = require("express");
const cors    = require("cors");
const { execFile } = require("child_process");
const fs   = require("fs");
const path = require("path");
const os   = require("os");
const crypto = require("crypto");

const app  = express();
const PORT = process.env.PORT || 3000;

// Allow requests from GitHub Pages and localhost dev
const ALLOWED_ORIGINS = [
  /^https:\/\/[\w-]+\.github\.io$/,
  /^http:\/\/localhost(:\d+)?$/,
  /^http:\/\/127\.0\.0\.1(:\d+)?$/,
];

app.use(cors({
  origin: (origin, cb) => {
    // Allow no-origin requests (e.g. curl, same-origin)
    if (!origin) return cb(null, true);
    const ok = ALLOWED_ORIGINS.some(r => r.test(origin));
    cb(ok ? null : new Error("Not allowed by CORS"), ok);
  }
}));

app.use(express.json({ limit: "64kb" }));

// Path to simc binary — lives at /app/simc in the Docker container,
// or relative to this file for local dev if you have a simc binary handy.
const SIMC_BIN = process.env.SIMC_BIN
  || path.join(__dirname, "..", "simc")
  || path.join(__dirname, "simc");

// ─── Helpers ─────────────────────────────────────────────────────────────────

function sanitizeOption(val, def, min, max) {
  const n = parseInt(val, 10);
  if (isNaN(n)) return def;
  return Math.min(Math.max(n, min), max);
}

// Parse simc stdout for the scale factors / EP weights table.
// Returns { dps, weights: { stat: value, ... }, raw: string }
function parseSimcOutput(stdout) {
  const result = { dps: null, weights: {}, error: null, raw: stdout };

  // DPS line: "  Player: Name ... DPS=12345.67"
  const dpsMatch = stdout.match(/DPS=([0-9.]+)/);
  if (dpsMatch) result.dps = parseFloat(dpsMatch[1]);

  // Scale factors block looks like:
  //   Scale Factors: Agility=1.23  AttackPower=0.45  ...
  // or a table:
  //   Stat    Value
  //   ------  -----
  //   Agi     1.23
  const sfBlock = stdout.match(/Scale Factors:([\s\S]*?)(?:\n\n|\nSimulation|\nDPS Ranking|$)/);
  if (sfBlock) {
    const tokens = sfBlock[1].match(/(\w+)=([0-9.+-]+)/g) || [];
    tokens.forEach(t => {
      const [k, v] = t.split("=");
      result.weights[k] = parseFloat(v);
    });
  }

  // Also try the columnar table format
  if (Object.keys(result.weights).length === 0) {
    const tableMatch = stdout.match(/Gains \(EP\)[\s\S]*?(?=\n\n)/);
    if (tableMatch) {
      const rows = tableMatch[0].split("\n").slice(2);
      rows.forEach(row => {
        const parts = row.trim().split(/\s+/);
        if (parts.length >= 2 && !isNaN(parseFloat(parts[1]))) {
          result.weights[parts[0]] = parseFloat(parts[1]);
        }
      });
    }
  }

  return result;
}

// Build the full .simc profile text from user-supplied export + options
function buildProfile(exportText, options) {
  const { targetLevel, iterations, threads } = options;
  const header = [
    `# Generated by simc-triumvirate`,
    `iterations=${iterations}`,
    `threads=${threads}`,
    `target_level=${targetLevel}`,
    `calculate_scale_factors=1`,
    `scale_only=hit,agi,ap,int,sp,sta,crit,haste,expertise`,
    ``,
  ].join("\n");
  return header + exportText;
}

// ─── Routes ──────────────────────────────────────────────────────────────────

app.get("/api/health", (_req, res) => {
  res.json({ ok: true, simc: SIMC_BIN });
});

app.post("/api/simulate", (req, res) => {
  const { profile: rawProfile, options: rawOptions = {} } = req.body || {};

  if (!rawProfile || typeof rawProfile !== "string") {
    return res.status(400).json({ error: "Missing profile text" });
  }
  if (rawProfile.length > 32768) {
    return res.status(400).json({ error: "Profile too large (max 32KB)" });
  }

  const options = {
    targetLevel: sanitizeOption(rawOptions.targetLevel, 63, 1, 83),
    iterations:  sanitizeOption(rawOptions.iterations,  5000, 100, 50000),
    threads:     sanitizeOption(rawOptions.threads,     2, 1, 8),
  };

  const profileText = buildProfile(rawProfile, options);

  // Write to a unique temp file
  const tmpFile = path.join(os.tmpdir(), `simc-${crypto.randomUUID()}.simc`);
  fs.writeFileSync(tmpFile, profileText, "utf8");

  const timeout = Math.max(30000, options.iterations * 4); // ~4ms per iteration headroom

  execFile(SIMC_BIN, [tmpFile], { timeout }, (err, stdout, stderr) => {
    fs.unlink(tmpFile, () => {}); // cleanup regardless

    if (err) {
      // simc exits non-zero on warnings too; check if we still got output
      if (!stdout) {
        console.error("simc error:", err.message, stderr);
        return res.status(500).json({
          error: "Simulation failed",
          detail: stderr || err.message,
        });
      }
    }

    const parsed = parseSimcOutput(stdout);
    res.json({
      ok: true,
      dps: parsed.dps,
      weights: parsed.weights,
      raw: stdout,
    });
  });
});

// ─── Start ───────────────────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(`simc-triumvirate backend running on port ${PORT}`);
  console.log(`simc binary: ${SIMC_BIN}`);
});
